package pl.sk.ocr.domain.issue;

public enum ProcessingStage {
    BOOTSTRAP,
    CONFIGURATION_LOADING,
    CONFIGURATION_VALIDATION,
    DOCUMENT_DISCOVERY,
    DOCUMENT_LOADING,
    PAGE_RENDERING,
    PAGE_PREPARATION,
    PAGE_OCR,
    CATEGORY_IDENTIFICATION,
    ANCHOR_DETECTION,
    GEOMETRY_RESOLUTION,
    FIELD_REGION_RESOLUTION,
    FIELD_CROP,
    IMAGE_PROCESSING,
    FIELD_OCR,
    VALUE_TRANSFORMATION,
    FIELD_VALIDATION,
    OUTPUT_WRITING,
    SOURCE_FILE_MOVE,
    BATCH_FINALIZATION
}
